[package]
name = "luc1d-imhentai"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs.git", rev = "e1320b0a2e11afb59e4dee374883a2212d325699" }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
[dev-dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs.git", rev = "e1320b0a2e11afb59e4dee374883a2212d325699", features = ["test"] }
aidoku-test = { git = "https://github.com/Aidoku/aidoku-rs.git", rev = "e1320b0a2e11afb59e4dee374883a2212d325699" }
[lib]
crate-type = ["cdylib"]
[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true
